# Generated by Django 3.2.23 on 2025-03-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('opis_truckstop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.CharField(max_length=50)),
                ('retail_price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
