# Generated by Django 3.2.23 on 2025-03-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelstation',
            old_name='truckstop_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fuelstation',
            old_name='retail_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='fuelstation',
            old_name='opis_truckstop_id',
            new_name='station_id',
        ),
    ]
