# Generated by Django 3.2.23 on 2025-03-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_route', '0002_auto_20250306_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='rack_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='station_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
